version: "3.9"

services:
  sample:
    container_name: verbose-bassoon-rr
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 1337:80 # do I need '' here?
    environment:
      - CHOKIDAR_USEPOLLING=true
