version: "3.9"

services:
  vb-dev:
    container_name: vb-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
